# Generated by Django 4.2.3 on 2023-10-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.FileField(upload_to='')),
                ('private_key', models.FileField(upload_to='')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
    ]
